# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.device_types_api import DeviceTypesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceTypesApi(unittest.TestCase):
    """DeviceTypesApi unit test stubs"""

    def setUp(self):
        self.api = api.device_types_api.DeviceTypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deletedevice_types_item(self):
        """Test case for deletedevice_types_item

        Deletes a device-types document  # noqa: E501
        """
        pass

    def test_getdevice_types(self):
        """Test case for getdevice_types

        Retrieves one or more device_types  # noqa: E501
        """
        pass

    def test_getdevice_types_item(self):
        """Test case for getdevice_types_item

        Retrieves a device-types document  # noqa: E501
        """
        pass

    def test_patchdevice_types_item(self):
        """Test case for patchdevice_types_item

        Updates a device-types document  # noqa: E501
        """
        pass

    def test_postdevice_types(self):
        """Test case for postdevice_types

        Stores one or more device_types.  # noqa: E501
        """
        pass

    def test_putdevice_types_item(self):
        """Test case for putdevice_types_item

        Replaces a device-types document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
