# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.preferences import Preferences  # noqa: E501
from swagger_client.rest import ApiException


class TestPreferences(unittest.TestCase):
    """Preferences unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreferences(self):
        """Test Preferences"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.preferences.Preferences()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
