# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.loraserver_core_api import LoraserverCoreApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLoraserverCoreApi(unittest.TestCase):
    """LoraserverCoreApi unit test stubs"""

    def setUp(self):
        self.api = api.loraserver_core_api.LoraserverCoreApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deleteloraserver_core_item(self):
        """Test case for deleteloraserver_core_item

        Deletes a loraserver-core document  # noqa: E501
        """
        pass

    def test_getloraserver_core(self):
        """Test case for getloraserver_core

        Retrieves one or more loraserver_core  # noqa: E501
        """
        pass

    def test_getloraserver_core_item(self):
        """Test case for getloraserver_core_item

        Retrieves a loraserver-core document  # noqa: E501
        """
        pass

    def test_patchloraserver_core_item(self):
        """Test case for patchloraserver_core_item

        Updates a loraserver-core document  # noqa: E501
        """
        pass

    def test_postloraserver_core(self):
        """Test case for postloraserver_core

        Stores one or more loraserver_core.  # noqa: E501
        """
        pass

    def test_putloraserver_core_item(self):
        """Test case for putloraserver_core_item

        Replaces a loraserver-core document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
