# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.organization_details_api import OrganizationDetailsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOrganizationDetailsApi(unittest.TestCase):
    """OrganizationDetailsApi unit test stubs"""

    def setUp(self):
        self.api = api.organization_details_api.OrganizationDetailsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deleteorganization_details_item(self):
        """Test case for deleteorganization_details_item

        Deletes a organization-details document  # noqa: E501
        """
        pass

    def test_getorg_details(self):
        """Test case for getorg_details

        Retrieves one or more org_details  # noqa: E501
        """
        pass

    def test_getorganization_details_item(self):
        """Test case for getorganization_details_item

        Retrieves a organization-details document  # noqa: E501
        """
        pass

    def test_patchorganization_details_item(self):
        """Test case for patchorganization_details_item

        Updates a organization-details document  # noqa: E501
        """
        pass

    def test_postorg_details(self):
        """Test case for postorg_details

        Stores one or more org_details.  # noqa: E501
        """
        pass

    def test_putorganization_details_item(self):
        """Test case for putorganization_details_item

        Replaces a organization-details document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
