# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.loraserver_core import LoraserverCore  # noqa: E501
from swagger_client.rest import ApiException


class TestLoraserverCore(unittest.TestCase):
    """LoraserverCore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoraserverCore(self):
        """Test LoraserverCore"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.loraserver_core.LoraserverCore()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
