# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import metacore_api_python_cli
from api.roles_api import RolesApi  # noqa: E501
from metacore_api_python_cli.rest import ApiException


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self):
        self.api = api.roles_api.RolesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deleteroles_item(self):
        """Test case for deleteroles_item

        Deletes a roles document  # noqa: E501
        """
        pass

    def test_getroles(self):
        """Test case for getroles

        Retrieves one or more roles  # noqa: E501
        """
        pass

    def test_getroles_item(self):
        """Test case for getroles_item

        Retrieves a roles document  # noqa: E501
        """
        pass

    def test_patchroles_item(self):
        """Test case for patchroles_item

        Updates a roles document  # noqa: E501
        """
        pass

    def test_postroles(self):
        """Test case for postroles

        Stores one or more roles.  # noqa: E501
        """
        pass

    def test_putroles_item(self):
        """Test case for putroles_item

        Replaces a roles document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
