# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import metacore_api_python_cli
from api.preferences_api import PreferencesApi  # noqa: E501
from metacore_api_python_cli.rest import ApiException


class TestPreferencesApi(unittest.TestCase):
    """PreferencesApi unit test stubs"""

    def setUp(self):
        self.api = api.preferences_api.PreferencesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deletepreferences_item(self):
        """Test case for deletepreferences_item

        Deletes a preferences document  # noqa: E501
        """
        pass

    def test_getpreferences(self):
        """Test case for getpreferences

        Retrieves one or more preferences  # noqa: E501
        """
        pass

    def test_getpreferences_item(self):
        """Test case for getpreferences_item

        Retrieves a preferences document  # noqa: E501
        """
        pass

    def test_patchpreferences_item(self):
        """Test case for patchpreferences_item

        Updates a preferences document  # noqa: E501
        """
        pass

    def test_postpreferences(self):
        """Test case for postpreferences

        Stores one or more preferences.  # noqa: E501
        """
        pass

    def test_putpreferences_item(self):
        """Test case for putpreferences_item

        Replaces a preferences document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
