# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.device_types import DeviceTypes  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceTypes(unittest.TestCase):
    """DeviceTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceTypes(self):
        """Test DeviceTypes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.device_types.DeviceTypes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
