# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import metacore_api_python_cli
from models.preferences_widgets import PreferencesWidgets  # noqa: E501
from metacore_api_python_cli.rest import ApiException


class TestPreferencesWidgets(unittest.TestCase):
    """PreferencesWidgets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPreferencesWidgets(self):
        """Test PreferencesWidgets"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metacore_api_python_cli.models.preferences_widgets.PreferencesWidgets()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
