# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.signup_api import SignupApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSignupApi(unittest.TestCase):
    """SignupApi unit test stubs"""

    def setUp(self):
        self.api = api.signup_api.SignupApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deletesignup_item(self):
        """Test case for deletesignup_item

        Deletes a signup document  # noqa: E501
        """
        pass

    def test_getsignup_item(self):
        """Test case for getsignup_item

        Retrieves a signup document  # noqa: E501
        """
        pass

    def test_patchsignup_item(self):
        """Test case for patchsignup_item

        Updates a signup document  # noqa: E501
        """
        pass

    def test_postsignup(self):
        """Test case for postsignup

        Stores one signup.  # noqa: E501
        """
        pass

    def test_putsignup_item(self):
        """Test case for putsignup_item

        Replaces a signup document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
