# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import metacore_api_python_cli
from api.organizations_api import OrganizationsApi  # noqa: E501
from metacore_api_python_cli.rest import ApiException


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = api.organizations_api.OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deleteorganizations_item(self):
        """Test case for deleteorganizations_item

        Deletes a organizations document  # noqa: E501
        """
        pass

    def test_getorganizations_item(self):
        """Test case for getorganizations_item

        Retrieves a organizations document  # noqa: E501
        """
        pass

    def test_getorgs(self):
        """Test case for getorgs

        Retrieves one or more orgs  # noqa: E501
        """
        pass

    def test_patchorganizations_item(self):
        """Test case for patchorganizations_item

        Updates a organizations document  # noqa: E501
        """
        pass

    def test_postorgs(self):
        """Test case for postorgs

        Stores one or more orgs.  # noqa: E501
        """
        pass

    def test_putorganizations_item(self):
        """Test case for putorganizations_item

        Replaces a organizations document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
