# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import metacore_api_python_cli
from models.error_error import ErrorError  # noqa: E501
from metacore_api_python_cli.rest import ApiException


class TestErrorError(unittest.TestCase):
    """ErrorError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorError(self):
        """Test ErrorError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = metacore_api_python_cli.models.error_error.ErrorError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
