# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from api.sensors_api import SensorsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSensorsApi(unittest.TestCase):
    """SensorsApi unit test stubs"""

    def setUp(self):
        self.api = api.sensors_api.SensorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deletesensors_item(self):
        """Test case for deletesensors_item

        Deletes a sensors document  # noqa: E501
        """
        pass

    def test_getsensors(self):
        """Test case for getsensors

        Retrieves one or more sensors  # noqa: E501
        """
        pass

    def test_getsensors_item(self):
        """Test case for getsensors_item

        Retrieves a sensors document  # noqa: E501
        """
        pass

    def test_patchsensors_item(self):
        """Test case for patchsensors_item

        Updates a sensors document  # noqa: E501
        """
        pass

    def test_postsensors(self):
        """Test case for postsensors

        Stores one or more sensors.  # noqa: E501
        """
        pass

    def test_putsensors_item(self):
        """Test case for putsensors_item

        Replaces a sensors document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
