# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import metacore_api_python_cli
from api.hardwares_api import HardwaresApi  # noqa: E501
from metacore_api_python_cli.rest import ApiException


class TestHardwaresApi(unittest.TestCase):
    """HardwaresApi unit test stubs"""

    def setUp(self):
        self.api = api.hardwares_api.HardwaresApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deletehardwares_item(self):
        """Test case for deletehardwares_item

        Deletes a hardwares document  # noqa: E501
        """
        pass

    def test_gethardwares(self):
        """Test case for gethardwares

        Retrieves one or more hardwares  # noqa: E501
        """
        pass

    def test_gethardwares_item(self):
        """Test case for gethardwares_item

        Retrieves a hardwares document  # noqa: E501
        """
        pass

    def test_patchhardwares_item(self):
        """Test case for patchhardwares_item

        Updates a hardwares document  # noqa: E501
        """
        pass

    def test_posthardwares(self):
        """Test case for posthardwares

        Stores one or more hardwares.  # noqa: E501
        """
        pass

    def test_puthardwares_item(self):
        """Test case for puthardwares_item

        Replaces a hardwares document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
