# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PreferencesWidgets(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'device_id': 'DevicesId',
        'sensors': 'list[PreferencesSensors]',
        'type': 'str',
        'uid': 'str'
    }

    attribute_map = {
        'device_id': 'deviceId',
        'sensors': 'sensors',
        'type': 'type',
        'uid': 'uid'
    }

    def __init__(self, device_id=None, sensors=None, type=None, uid=None):  # noqa: E501
        """PreferencesWidgets - a model defined in Swagger"""  # noqa: E501
        self._device_id = None
        self._sensors = None
        self._type = None
        self._uid = None
        self.discriminator = None
        if device_id is not None:
            self.device_id = device_id
        if sensors is not None:
            self.sensors = sensors
        if type is not None:
            self.type = type
        self.uid = uid

    @property
    def device_id(self):
        """Gets the device_id of this PreferencesWidgets.  # noqa: E501


        :return: The device_id of this PreferencesWidgets.  # noqa: E501
        :rtype: DevicesId
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this PreferencesWidgets.


        :param device_id: The device_id of this PreferencesWidgets.  # noqa: E501
        :type: DevicesId
        """

        self._device_id = device_id

    @property
    def sensors(self):
        """Gets the sensors of this PreferencesWidgets.  # noqa: E501


        :return: The sensors of this PreferencesWidgets.  # noqa: E501
        :rtype: list[PreferencesSensors]
        """
        return self._sensors

    @sensors.setter
    def sensors(self, sensors):
        """Sets the sensors of this PreferencesWidgets.


        :param sensors: The sensors of this PreferencesWidgets.  # noqa: E501
        :type: list[PreferencesSensors]
        """

        self._sensors = sensors

    @property
    def type(self):
        """Gets the type of this PreferencesWidgets.  # noqa: E501


        :return: The type of this PreferencesWidgets.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PreferencesWidgets.


        :param type: The type of this PreferencesWidgets.  # noqa: E501
        :type: str
        """
        allowed_values = ["device", "events", "map", "singlestat", "weather_forecast"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def uid(self):
        """Gets the uid of this PreferencesWidgets.  # noqa: E501


        :return: The uid of this PreferencesWidgets.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this PreferencesWidgets.


        :param uid: The uid of this PreferencesWidgets.  # noqa: E501
        :type: str
        """
        if uid is None:
            raise ValueError("Invalid value for `uid`, must not be `None`")  # noqa: E501

        self._uid = uid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PreferencesWidgets, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PreferencesWidgets):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
