# coding: utf-8

"""
    Metacore IoT Object Storage API

    Metacore Object Storage - IOT Core Services  # noqa: E501

    OpenAPI spec version: 0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class SignupApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def deletesignup_item(self, signup_id, if_match, **kwargs):  # noqa: E501
        """Deletes a signup document  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.deletesignup_item(signup_id, if_match, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str signup_id: (required)
        :param str if_match: Current value of the _etag field (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.deletesignup_item_with_http_info(signup_id, if_match, **kwargs)  # noqa: E501
        else:
            (data) = self.deletesignup_item_with_http_info(signup_id, if_match, **kwargs)  # noqa: E501
            return data

    def deletesignup_item_with_http_info(self, signup_id, if_match, **kwargs):  # noqa: E501
        """Deletes a signup document  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.deletesignup_item_with_http_info(signup_id, if_match, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str signup_id: (required)
        :param str if_match: Current value of the _etag field (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['signup_id', 'if_match']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method deletesignup_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'signup_id' is set
        if ('signup_id' not in params or
                params['signup_id'] is None):
            raise ValueError("Missing the required parameter `signup_id` when calling `deletesignup_item`")  # noqa: E501
        # verify the required parameter 'if_match' is set
        if ('if_match' not in params or
                params['if_match'] is None):
            raise ValueError("Missing the required parameter `if_match` when calling `deletesignup_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'signup_id' in params:
            path_params['signupId'] = params['signup_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'if_match' in params:
            header_params['If-Match'] = params['if_match']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/signup/{signupId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def getsignup_item(self, signup_id, **kwargs):  # noqa: E501
        """Retrieves a signup document  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.getsignup_item(signup_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str signup_id: (required)
        :return: Signup
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.getsignup_item_with_http_info(signup_id, **kwargs)  # noqa: E501
        else:
            (data) = self.getsignup_item_with_http_info(signup_id, **kwargs)  # noqa: E501
            return data

    def getsignup_item_with_http_info(self, signup_id, **kwargs):  # noqa: E501
        """Retrieves a signup document  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.getsignup_item_with_http_info(signup_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str signup_id: (required)
        :return: Signup
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['signup_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method getsignup_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'signup_id' is set
        if ('signup_id' not in params or
                params['signup_id'] is None):
            raise ValueError("Missing the required parameter `signup_id` when calling `getsignup_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'signup_id' in params:
            path_params['signupId'] = params['signup_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/signup/{signupId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Signup',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def patchsignup_item(self, body, if_match, signup_id, **kwargs):  # noqa: E501
        """Updates a signup document  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patchsignup_item(body, if_match, signup_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Signup body: A signup document. (required)
        :param str if_match: Current value of the _etag field (required)
        :param str signup_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.patchsignup_item_with_http_info(body, if_match, signup_id, **kwargs)  # noqa: E501
        else:
            (data) = self.patchsignup_item_with_http_info(body, if_match, signup_id, **kwargs)  # noqa: E501
            return data

    def patchsignup_item_with_http_info(self, body, if_match, signup_id, **kwargs):  # noqa: E501
        """Updates a signup document  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.patchsignup_item_with_http_info(body, if_match, signup_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Signup body: A signup document. (required)
        :param str if_match: Current value of the _etag field (required)
        :param str signup_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'if_match', 'signup_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method patchsignup_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `patchsignup_item`")  # noqa: E501
        # verify the required parameter 'if_match' is set
        if ('if_match' not in params or
                params['if_match'] is None):
            raise ValueError("Missing the required parameter `if_match` when calling `patchsignup_item`")  # noqa: E501
        # verify the required parameter 'signup_id' is set
        if ('signup_id' not in params or
                params['signup_id'] is None):
            raise ValueError("Missing the required parameter `signup_id` when calling `patchsignup_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'signup_id' in params:
            path_params['signupId'] = params['signup_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'if_match' in params:
            header_params['If-Match'] = params['if_match']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/signup/{signupId}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def postsignup(self, body, **kwargs):  # noqa: E501
        """Stores one signup.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.postsignup(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Signup body: A signup document. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.postsignup_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.postsignup_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def postsignup_with_http_info(self, body, **kwargs):  # noqa: E501
        """Stores one signup.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.postsignup_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Signup body: A signup document. (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method postsignup" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `postsignup`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/signup', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def putsignup_item(self, body, if_match, signup_id, **kwargs):  # noqa: E501
        """Replaces a signup document  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.putsignup_item(body, if_match, signup_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Signup body: A signup document. (required)
        :param str if_match: Current value of the _etag field (required)
        :param str signup_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.putsignup_item_with_http_info(body, if_match, signup_id, **kwargs)  # noqa: E501
        else:
            (data) = self.putsignup_item_with_http_info(body, if_match, signup_id, **kwargs)  # noqa: E501
            return data

    def putsignup_item_with_http_info(self, body, if_match, signup_id, **kwargs):  # noqa: E501
        """Replaces a signup document  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.putsignup_item_with_http_info(body, if_match, signup_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Signup body: A signup document. (required)
        :param str if_match: Current value of the _etag field (required)
        :param str signup_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'if_match', 'signup_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method putsignup_item" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `putsignup_item`")  # noqa: E501
        # verify the required parameter 'if_match' is set
        if ('if_match' not in params or
                params['if_match'] is None):
            raise ValueError("Missing the required parameter `if_match` when calling `putsignup_item`")  # noqa: E501
        # verify the required parameter 'signup_id' is set
        if ('signup_id' not in params or
                params['signup_id'] is None):
            raise ValueError("Missing the required parameter `signup_id` when calling `putsignup_item`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'signup_id' in params:
            path_params['signupId'] = params['signup_id']  # noqa: E501

        query_params = []

        header_params = {}
        if 'if_match' in params:
            header_params['If-Match'] = params['if_match']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['api_key']  # noqa: E501

        return self.api_client.call_api(
            '/signup/{signupId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
